export const legalSections = [
  {
    id: "terms",
    title: "Terms & Conditions",
    subtitle: "Please read these terms carefully before using our platform.",
    lastUpdated: "June 2026",
    content: [
      {
        type: "paragraph",
        text: "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
      },
      {
        type: "paragraph",
        text: "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://www.stayo.app ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').",
      },
      {
        type: "paragraph",
        text: "The Platform is owned by StayO, with its registered office at [Registered address — TBD] (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').",
      },
      {
        type: "paragraph",
        text: "Your use of the Platform and services and tools are governed by the following terms and conditions (\"Terms of Use\") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.",
      },
      {
        type: "paragraph",
        text: "For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any tenant, resident, or customer who has agreed to become a user/buyer on the Platform.",
      },
      {
        type: "notice",
        text: "ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.",
      },
      {
        type: "subheading",
        text: "Platform Usage & Services",
      },
      {
        type: "paragraph",
        text: "StayO operates this Platform to facilitate tenant onboarding, room allocations, agreement generation, digital check-in, fee payments, and related communication. Accommodation services are provided at our physical premises at [Registered address — TBD].",
      },
      {
        type: "subheading",
        text: "Your Obligations",
      },
      {
        type: "paragraph",
        text: "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",
      },
      {
        type: "paragraph",
        text: "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.",
      },
      {
        type: "paragraph",
        text: "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",
      },
      {
        type: "paragraph",
        text: "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents include and are not limited to the design, layout, look and graphics.",
      },
      {
        type: "paragraph",
        text: "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.",
      },
      {
        type: "paragraph",
        text: "You agree to pay us the charges associated with availing the Services, including rent, security deposits, late fees, and utilities, in a timely manner.",
      },
      {
        type: "paragraph",
        text: "You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you. Prohibited activities include but are not limited to attempting to bypass payment mechanisms, hacking the platform, or submitting false tenant identification.",
      },
      {
        type: "paragraph",
        text: "You agree and acknowledge that the website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.",
      },
      {
        type: "paragraph",
        text: "You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.",
      },
      {
        type: "subheading",
        text: "Indemnification",
      },
      {
        type: "paragraph",
        text: "You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of these Terms of Use, Privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.",
      },
      {
        type: "subheading",
        text: "Limitation of Liability",
      },
      {
        type: "paragraph",
        text: "In no event shall StayO or its representatives be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the Platform or the physical services provided.",
      },
      {
        type: "subheading",
        text: "Force Majeure",
      },
      {
        type: "paragraph",
        text: "Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.",
      },
      {
        type: "subheading",
        text: "Governing Law & Jurisdiction",
      },
      {
        type: "paragraph",
        text: "These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.",
      },
      {
        type: "paragraph",
        text: "All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Hyderabad, India.",
      },
      {
        type: "paragraph",
        text: "All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.",
      },
    ],
  },
  {
    id: "privacy",
    title: "Privacy Policy",
    subtitle: "How we collect, use, and protect your personal information.",
    lastUpdated: "June 2026",
    content: [
      {
        type: "subheading",
        text: "Introduction",
      },
      {
        type: "paragraph",
        text: "This Privacy Policy describes how StayO (collectively \"StayO, we, our, us\") collect, use, share, protect or otherwise process your information/personal data through our website https://www.stayo.app (hereinafter referred to as Platform). Please note that you may be able to browse certain sections of the Platform without registering with us. We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India. By visiting this Platform, providing your information or availing any product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and the applicable service/product terms and conditions, and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.",
      },
      {
        type: "subheading",
        text: "Collection of Information",
      },
      {
        type: "paragraph",
        text: "We collect your personal data when you use our Platform, services or otherwise interact with us during the course of our relationship. Some of the information that we may collect includes but is not limited to personal information provided to us during sign-up/registering or using our Platform such as name, date of birth, address, telephone/mobile number, email ID, parent/guardian contact details, and documents shared as proof of identity or address.",
      },
      {
        type: "paragraph",
        text: "Payment processing: Online payments on our platform are processed securely via our integration with Razorpay. During transactions, payment details like transaction IDs, payment method, and amount are shared. We do not store sensitive payment credentials such as credit card numbers, debit card numbers, or net banking passwords on our servers.",
      },
      {
        type: "paragraph",
        text: "We may track your behaviour, preferences, and other information that you choose to provide on our Platform. This information is compiled and analysed on an aggregated basis. We will also collect your information related to your transactions on Platform and such third-party business partner platforms.",
      },
      {
        type: "notice",
        text: "If you receive an email or a call from a person/association claiming to be StayO seeking personal data like debit/credit card PIN, net-banking or mobile banking password, never provide such information. Report any such incident immediately to an appropriate law enforcement agency.",
      },
      {
        type: "subheading",
        text: "Usage of Personal Data",
      },
      {
        type: "paragraph",
        text: "We use personal data to provide the services you request. We use your personal data to handle tenant admissions, manage allocations, process rent and late fee calculations, handle secure payments, resolve disputes, troubleshoot problems, customize your experience, detect and protect us against error, fraud and other criminal activity, and enforce our terms and conditions.",
      },
      {
        type: "subheading",
        text: "Sharing of Information",
      },
      {
        type: "paragraph",
        text: "We may share your personal data internally within our group entities, our other corporate entities, and affiliates to provide you access to the services and products offered by them.",
      },
      {
        type: "paragraph",
        text: "We may disclose personal data to third parties such as payment gateways (Razorpay), business partners, or third party service providers. These disclosures are required for us to provide you access to our services, to comply with our legal obligations, to enforce our user agreement, and to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our services.",
      },
      {
        type: "paragraph",
        text: "We may disclose personal and sensitive personal data to government agencies or other authorised law enforcement agencies if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process.",
      },
      {
        type: "subheading",
        text: "Security Precautions",
      },
      {
        type: "paragraph",
        text: "To protect your personal data from unauthorised access or disclosure, loss or misuse we adopt reasonable security practices and procedures. Once your information is in our possession or whenever you access your account information, we adhere to our security guidelines to protect it against unauthorised access. However, the transmission of information is not completely secure for reasons beyond our control. By using the Platform, the users accept the security implications of data transmission over the internet. Users are responsible for ensuring the protection of login and password records for their account.",
      },
      {
        type: "subheading",
        text: "Data Deletion and Retention",
      },
      {
        type: "paragraph",
        text: "You have an option to request the deletion of your account. Please write to us at the contact information provided below to assist you with these requests. We may refuse or delay deletion in the event of any pending grievance, outstanding payments, or active residency agreement obligations. Once the account is deleted, you will lose access to the account.",
      },
      {
        type: "paragraph",
        text: "We retain your personal data for a period no longer than is required for the purpose for which it was collected or as required under any applicable law (such as financial records retention).",
      },
      {
        type: "subheading",
        text: "Consent",
      },
      {
        type: "paragraph",
        text: "By visiting our Platform or by providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information on the Platform in accordance with this Privacy Policy. If you disclose to us any personal data relating to other people, you represent that you have the authority to do so.",
      },
      {
        type: "paragraph",
        text: "You, while providing your personal data over the Platform or any partner platforms, consent to us contacting you through SMS, instant messaging apps (WhatsApp), call and/or e-mail for the purposes specified in this Privacy Policy.",
      },
    ],
  },
  {
    id: "refund",
    title: "Refund & Cancellation Policy",
    subtitle: "Our policy regarding payments, deposits, and refunds.",
    lastUpdated: "June 2026",
    content: [
      {
        type: "paragraph",
        text: "All payments made to StayO for rent, admission fees, or advance security deposits are generally non-refundable once credited toward accommodation obligations.",
      },
      {
        type: "paragraph",
        text: "In the event of accidental or duplicate transactions made during the online payment process, tenants may request a review by presenting transaction receipts and payment details to the hostel management.",
      },
      {
        type: "paragraph",
        text: "If a refund is approved by the management after verification of the claim, the refund amount will be credited back to the original bank account or payment method within 7 to 10 business days.",
      },
      {
        type: "paragraph",
        text: "Cancellation of admissions or booking reservations must be submitted in writing. The refundability of any initial token deposit is subject to the terms of the individual reservation agreement, and hostel management reserves final review and approval rights.",
      },
      {
        type: "subheading",
        text: "Contact for Payment Queries",
      },
      {
        type: "contact_list",
        items: [
          { label: "Name", value: "Chidiri Shiva Prakash" },
          { label: "Email", value: "spchidiri2006@gmail.com" },
          { label: "Mobile", value: "+91 8008046952" },
        ],
      },
    ],
  },
  {
    id: "shipping",
    title: "Shipping & Delivery Policy",
    subtitle: "Information regarding digital service delivery.",
    lastUpdated: "June 2026",
    content: [
      {
        type: "paragraph",
        text: "StayO provides student and working professional accommodation services. No physical products are shipped or delivered as part of our operations.",
      },
      {
        type: "paragraph",
        text: "All services are provided digitally through our online hostel management platform. Payment confirmations, fee receipts, digital check-ins, and hostel residency agreements are generated digitally and delivered via email or inside the tenant portal.",
      },
      {
        type: "paragraph",
        text: "Access to the hostel rooms and associated physical amenities (such as Wi-Fi, dining, and laundry) becomes active and available immediately after successful tenant onboarding, verification, agreement execution, and payment confirmation.",
      },
    ],
  },
  {
    id: "contact",
    title: "Contact Us",
    subtitle: "Grievance redressal and business contact details.",
    lastUpdated: "June 2026",
    content: [
      {
        type: "paragraph",
        text: "If you have any questions about our services, admissions, billing, or if you wish to report a grievance, please contact us using the details below:",
      },
      {
        type: "subheading",
        text: "Customer Support & Grievances",
      },
      {
        type: "contact_list",
        items: [
          { label: "Customer Support", value: "Chidiri Shiva Prakash" },
          { label: "Grievance Officer", value: "Chidiri Shiva Prakash" },
          { label: "Business Email", value: "support@stayo.app" },
          { label: "Grievance Email", value: "spchidiri2006@gmail.com" },
          { label: "Mobile", value: "[Phone — TBD]" },
          { label: "Support Mobile", value: "+91 7901070333" },
          { label: "Grievance Phone", value: "+91 8008046952" },
          { label: "Registered Office", value: "StayO, [Registered address — TBD]" },
        ],
      },
    ],
  },
  {
    id: "data-deletion",
    title: "Data Deletion Instructions",
    subtitle: "How to request the deletion of your account and personal data.",
    lastUpdated: "June 2026",
    content: [
      {
        type: "paragraph",
        text: "StayO is committed to protecting your privacy and ensuring transparency regarding your personal data. If you have used our platform, registered an account, or logged in, you have the right to request the deletion of your data in accordance with applicable policies.",
      },
      {
        type: "subheading",
        text: "How to Request Data Deletion",
      },
      {
        type: "paragraph",
        text: "You can request the deletion of your account and all associated personal information (including name, phone number, email, and billing records) through either of the following methods:",
      },
      {
        type: "paragraph",
        text: "1. Self-Service Deletion: Log in to your StayO account, go to Profile/Settings, and click on 'Delete Account'. Please note that this action is permanent and cannot be undone.",
      },
      {
        type: "paragraph",
        text: "2. Contact Support: Send a formal email request to our Data Officer at spchidiri2006@gmail.com with the subject line 'Personal Data Deletion Request'. Please include your registered mobile number and full name to help us identify your account.",
      },
      {
        type: "subheading",
        text: "Processing Timeframe",
      },
      {
        type: "paragraph",
        text: "Upon receiving your request, we will verify your identity and delete your personal data within 30 business days. Once deleted, you will lose access to all associated portals and services.",
      },
      {
        type: "subheading",
        text: "Data Retention Exceptions",
      },
      {
        type: "paragraph",
        text: "Please note that we may retain certain records (such as transaction receipts, invoices, and legally binding residency agreements) where we are required to do so by law, to resolve pending payment disputes, or to comply with active audit requirements under Indian laws.",
      },
      {
        type: "subheading",
        text: "Contact for Data Deletion Inquiries",
      },
      {
        type: "contact_list",
        items: [
          { label: "Data Officer", value: "Chidiri Shiva Prakash" },
          { label: "Email", value: "spchidiri2006@gmail.com" },
          { label: "Phone", value: "+91 8008046952" },
        ],
      },
    ],
  },
];
