export const dynamic = "force-dynamic";
export const runtime = "nodejs";

import { NextRequest } from "next/server";
import { getSession, apiResponse, apiError } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { requireHostelBelongsToOwner } from "@/lib/security/scoped-query";
import { obligationEngine, OBLIGATION_TYPES } from "@/src/services/payments/obligation-engine";
import { financialLifecycleService } from "@/src/services/payments/financial-lifecycle-service";

/**
 * POST /api/payments/obligations
 * Create a financial obligation for a tenant.
 *
 * Supports all canonical obligation types (RENT, SECURITY_DEPOSIT, ADMISSION,
 * MAINTENANCE, LATE_FEE, FINE, EXTRA_CHARGE, DAMAGE, UTILITY, ADDITIONAL_CHARGE, OTHER).
 *
 * RENT obligations are typically auto-generated by the rent generation service,
 * but can be manually created here for corrections or ad-hoc billing.
 *
 * Body: {
 *   tenant_id,
 *   obligation_type,
 *   amount,
 *   rent_month,   // ISO date string — the month this charge belongs to
 *   due_date,     // ISO date string
 *   description?, // Owner-provided description
 *   notes?        // Internal notes
 * }
 * Auth: OWNER or ADMIN only
 */
export async function POST(req: NextRequest) {
  const session = await getSession(req);
  if (!session || !["OWNER", "ADMIN"].includes(session.role)) {
    return apiError("Forbidden", "FORBIDDEN", 403);
  }

  let obligation_type_label = "charge";
  try {
    const body = await req.json();
    const { tenant_id, obligation_type, amount, rent_month, due_date, description, notes } = body;
    obligation_type_label = obligation_type || "charge";

    // Validation
    if (!tenant_id) return apiError("tenant_id is required", "VALIDATION_ERROR", 400);
    if (!OBLIGATION_TYPES.includes(obligation_type)) {
      return apiError(
        `obligation_type must be one of: ${OBLIGATION_TYPES.join(", ")}`,
        "VALIDATION_ERROR", 400
      );
    }
    if (!amount || typeof amount !== "number" || amount <= 0) {
      return apiError("amount must be a positive number", "VALIDATION_ERROR", 400);
    }
    if (!rent_month) return apiError("rent_month is required", "VALIDATION_ERROR", 400);
    if (!due_date) return apiError("due_date is required", "VALIDATION_ERROR", 400);

    const rentMonthDate = new Date(rent_month);
    const dueDateDate = new Date(due_date);
    if (isNaN(rentMonthDate.getTime())) return apiError("rent_month is not a valid date", "VALIDATION_ERROR", 400);
    if (isNaN(dueDateDate.getTime())) return apiError("due_date is not a valid date", "VALIDATION_ERROR", 400);

    // Verify tenant belongs to this owner
    const tenant = await prisma.tenants.findUnique({
      where: { id: tenant_id },
      select: {
        owner_id: true,
        hostel_id: true,
        status: true,
        room_allocations: {
          where: { is_active: true },
          select: { id: true, hostel_id: true, room: { select: { hostel_id: true } } },
        },
      },
    });

    if (!tenant) return apiError("Tenant not found", "NOT_FOUND", 404);

    const ownerId = session.role === "OWNER" ? session.sub : session.sub;
    if (tenant.owner_id !== ownerId) {
      return apiError("Tenant does not belong to your account", "FORBIDDEN", 403);
    }
    if (tenant.status !== "ACTIVE") {
      return apiError("Manual obligations can only be created for ACTIVE tenants", "VALIDATION_ERROR", 400);
    }

    if (!tenant.hostel_id) {
      return apiError("Tenant is missing hostel context", "HOSTEL_CONTEXT_REQUIRED", 400);
    }
    await requireHostelBelongsToOwner(ownerId, tenant.hostel_id);

    const activeAllocation = (tenant as any).room_allocations[0] || null;
    const activeAllocationId = activeAllocation?.id || null;
    if (activeAllocation && activeAllocation.hostel_id !== tenant.hostel_id) {
      return apiError("Active allocation hostel does not match tenant hostel", "HOSTEL_CONTEXT_MISMATCH", 409);
    }
    if (activeAllocation?.room?.hostel_id && activeAllocation.room.hostel_id !== tenant.hostel_id) {
      return apiError("Active room hostel does not match tenant hostel", "HOSTEL_CONTEXT_MISMATCH", 409);
    }

    // Create the obligation via the engine, then activate it (synchronous
    // credit sweep) inside the same transaction when immediately payable.
    const obligation = await prisma.$transaction(async (tx: any) => {
      const created = await obligationEngine.createObligationInTx(tx, {
        tenantId: tenant_id,
        ownerId,
        hostelId: tenant.hostel_id!,
        allocationId: activeAllocationId,
        obligationType: obligation_type,
        amount,
        dueDate: dueDateDate,
        rentMonth: rentMonthDate,
        description: description || null,
        notes: notes || null,
        createdBy: session.sub,
      });
      if (created.status !== "DRAFT") {
        await financialLifecycleService.activatePayableObligations(tx, {
          tenantId: tenant_id,
          ownerId,
          hostelId: tenant.hostel_id!,
          obligationIds: [created.id],
        });
      }
      return created;
    });

    // Post-commit: notify (cache invalidation + SSE). Activation itself
    // already happened synchronously inside the transaction above.
    financialLifecycleService.notifyActivated({
      tenantId: tenant_id,
      ownerId,
      hostelId: tenant.hostel_id!,
      source: "manual_obligation_api",
    });

    return apiResponse(obligation, 201);
  } catch (error: any) {
    const msg = String(error?.message ?? error);
    // Prisma unique constraint: duplicate obligation for this month + type + allocation
    if (msg.includes("Unique constraint") || msg.includes("P2002")) {
      return apiError(
        `A ${obligation_type_label} obligation already exists for this tenant/month. ` +
        "Update the existing one or choose a different month.",
        "VALIDATION_ERROR", 409
      );
    }
    if (msg.includes("NOT_FOUND")) return apiError(msg, "NOT_FOUND", 404);
    if (msg.includes("FORBIDDEN")) return apiError(msg, "FORBIDDEN", 403);
    if (msg.includes("BAD_REQUEST")) return apiError(msg, "BAD_REQUEST", 400);
    return apiError(msg, "INTERNAL_ERROR", 500);
  }
}
