import { describe, expect, it } from 'vitest';
import {
  CHARGE_TYPES,
  chargeTypeLabel,
  resolveBillingMonth,
  summariseCharge,
  validateChargeDraft,
  type ChargeDraft,
} from './chargeDraft';

/**
 * The rules behind creating a manual charge.
 *
 * The old form defaulted the type to **Rent Installment**, which is the one
 * type an owner should almost never create by hand — rent is generated by the
 * monthly cron, so a manual one silently double-bills the tenant for a month
 * they already owe. It also asked for the owner's password on every charge,
 * fetched an identity token, and then never sent it: `POST
 * /payments/obligations` takes no token, so the prompt guarded nothing.
 */

function draft(overrides: Partial<ChargeDraft> = {}): ChargeDraft {
  return {
    type: 'UTILITY',
    amount: '500',
    dueDate: '2026-09-05',
    billingMonth: '',
    description: '',
    notes: '',
    ...overrides,
  };
}

describe('validateChargeDraft', () => {
  it('accepts a complete draft', () => {
    expect(validateChargeDraft(draft()).valid).toBe(true);
  });

  it('requires the owner to choose a type rather than defaulting to rent', () => {
    const result = validateChargeDraft(draft({ type: '' }));
    expect(result.valid).toBe(false);
    expect(result.errors.type).toBeTruthy();
  });

  it('rejects a missing amount', () => {
    expect(validateChargeDraft(draft({ amount: '' })).errors.amount).toBeTruthy();
  });

  it('rejects zero and negative amounts', () => {
    expect(validateChargeDraft(draft({ amount: '0' })).errors.amount).toBeTruthy();
    expect(validateChargeDraft(draft({ amount: '-40' })).errors.amount).toBeTruthy();
  });

  it('rejects an amount that is not a number', () => {
    expect(validateChargeDraft(draft({ amount: 'abc' })).errors.amount).toBeTruthy();
  });

  it('rejects a missing due date', () => {
    expect(validateChargeDraft(draft({ dueDate: '' })).errors.dueDate).toBeTruthy();
  });

  it('rejects an unparseable due date', () => {
    expect(validateChargeDraft(draft({ dueDate: 'not-a-date' })).errors.dueDate).toBeTruthy();
  });

  it('does not require a description or notes', () => {
    const result = validateChargeDraft(draft({ description: '', notes: '' }));
    expect(result.valid).toBe(true);
  });

  it('reports every problem at once rather than one at a time', () => {
    const result = validateChargeDraft(draft({ type: '', amount: '', dueDate: '' }));
    expect(Object.keys(result.errors).sort()).toEqual(['amount', 'dueDate', 'type']);
  });
});

describe('resolveBillingMonth', () => {
  it('defaults to the first of the due date’s month', () => {
    expect(resolveBillingMonth('2026-09-05', '')).toBe('2026-09-01T00:00:00.000Z');
  });

  it('uses an explicit billing month when the owner sets one', () => {
    expect(resolveBillingMonth('2026-09-05', '2026-07')).toBe('2026-07-01T00:00:00.000Z');
  });

  it('does not drift across a month boundary in a negative timezone', () => {
    // "2026-09-01" parsed as local time in UTC-5 is 31 Aug — which would file
    // a September charge under August. Everything here is computed in UTC.
    expect(resolveBillingMonth('2026-09-01', '')).toBe('2026-09-01T00:00:00.000Z');
  });

  it('returns null for an unusable due date instead of an Invalid Date', () => {
    expect(resolveBillingMonth('nonsense', '')).toBeNull();
  });
});

describe('CHARGE_TYPES', () => {
  it('does not put rent first, where it would be the accidental choice', () => {
    expect(CHARGE_TYPES[0].value).not.toBe('RENT');
  });

  it('marks rent as needing care, since the cron already generates it', () => {
    const rent = CHARGE_TYPES.find((t) => t.value === 'RENT');
    expect(rent?.caution).toBeTruthy();
  });

  it('offers a billing month only where the charge belongs to a month', () => {
    const rent = CHARGE_TYPES.find((t) => t.value === 'RENT');
    const damage = CHARGE_TYPES.find((t) => t.value === 'DAMAGE');
    expect(rent?.billingMonthApplies).toBe(true);
    expect(damage?.billingMonthApplies).toBe(false);
  });

  it('covers every type the backend accepts', () => {
    // Mirrors OBLIGATION_TYPES in obligation-engine.ts; a value the backend
    // rejects would fail only after the owner filled the whole form.
    expect(CHARGE_TYPES.map((t) => t.value).sort()).toEqual(
      [
        'ADDITIONAL_CHARGE', 'ADMISSION', 'DAMAGE', 'EXTRA_CHARGE', 'FINE',
        'LATE_FEE', 'MAINTENANCE', 'OTHER', 'RENT', 'SECURITY_DEPOSIT', 'UTILITY',
      ].sort(),
    );
  });
});

describe('chargeTypeLabel', () => {
  it('names a known type', () => {
    expect(chargeTypeLabel('UTILITY')).toBe('Utility');
  });

  it('falls back to the raw value rather than rendering blank', () => {
    expect(chargeTypeLabel('SOMETHING_NEW')).toBe('SOMETHING_NEW');
  });
});

describe('summariseCharge', () => {
  it('states what is about to be charged', () => {
    // Month abbreviation is left to the platform's `en-IN` (Sep vs Sept
    // varies by CLDR version) — the app formats every other date the same
    // way, so consistency matters more than pinning one spelling.
    const line = summariseCharge(draft({ type: 'UTILITY', amount: '500', dueDate: '2026-09-05' }));
    expect(line).toMatch(/^₹500 · Utility · due 05 Sept? 2026$/);
  });

  it('groups thousands the way the rest of the app does', () => {
    expect(summariseCharge(draft({ amount: '16000' }))).toContain('₹16,000');
  });

  it('says nothing until there is something to say', () => {
    expect(summariseCharge(draft({ amount: '' }))).toBeNull();
    expect(summariseCharge(draft({ dueDate: '' }))).toBeNull();
    expect(summariseCharge(draft({ type: '' }))).toBeNull();
  });
});
