/**
 * Payment Provider Adapter Contract — Phase 8
 *
 * The adapter boundary isolates five operational concerns from the rest
 * of HMS, so treasury, owner-facing finance, reconciliation, and core
 * payment workflows can stay completely provider-agnostic:
 *
 *   1. payment creation        — createIntent()
 *   2. webhook verification    — verifyWebhook()
 *   3. payment status lookup   — fetchStatus()
 *   4. refunds                 — refund() (optional capability)
 *   5. settlement metadata     — getSettlementMetadata() (optional capability)
 *
 * Architectural invariants:
 *
 *  A-1  THIN. The adapter exposes the operational surface only. It does
 *       not own idempotency, audit logging, ledger writes, or owner
 *       attribution. Those live in `payment-service` and are completely
 *       provider-agnostic.
 *
 *  A-2  CANONICAL STATES. Every adapter normalises provider-specific
 *       state strings into the `PAYMENT_STATE` enum below. Treasury
 *       and reconciliation only ever see canonical values. Provider
 *       raw values are preserved on `provider_state` / `raw_*` fields
 *       for debugging.
 *
 *  A-3  NORMALISED RESULT SHAPES. All adapter methods return strict
 *       result objects with the same canonical fields:
 *         - merchant_txn_id      (canonical, generated by us)
 *         - provider_transaction_id / provider_order_id / provider_reference_id
 *         - status               (canonical PAYMENT_STATE)
 *         - timestamps           (created_at / completed_at where available)
 *         - verification_state   (SIGNED / UNVERIFIED / SIGNATURE_FAILED)
 *         - raw_*                (provider's verbatim payload for forensics)
 *
 *  A-4  IDEMPOTENCY-FRIENDLY. Adapters MUST be safe to call repeatedly
 *       with the same merchant_txn_id and produce identical observable
 *       outcomes for the same provider state. Duplicate webhook delivery
 *       is handled at the payment-service layer (status lock + provider
 *       source-of-truth re-fetch), but the adapter must not assume
 *       single-delivery.
 *
 *  A-5  CREDENTIAL ISOLATION. Adapters receive their credentials from
 *       `merchant-context.ts`, never directly from process.env at the
 *       call site. The merchant context distinguishes hostel-owned UPI
 *       vs HMS-platform credentials. The adapter must accept its config
 *       through the constructor only.
 *
 *  A-6  NO TERMINOLOGY LEAKS. Adapter return values never use provider
 *       names in business fields ("PhonePe" is fine in raw_response, but
 *       `status` must be `"SUCCESS"`, not `"COMPLETED"` or `"CAPTURED"`).
 *       Owner-facing and treasury layers reject provider strings.
 *
 *  A-7  FUTURE-READY. The adapter is designed to accept sub-merchant /
 *       split-settlement context via metadata fields without breaking
 *       existing single-merchant flows.
 */

// ────────────────────────────────────────────────────────────────────────────
//  Canonical payment states (A-2)
// ────────────────────────────────────────────────────────────────────────────

/**
 * Canonical, provider-agnostic payment states. Map provider-specific
 * strings into these values via `mapProviderState()` or per-adapter
 * inline logic. Treasury and reconciliation only consume these values.
 */
export const PAYMENT_STATE = {
  /** Intent was created on the provider but the user has not yet paid. */
  CREATED:  "CREATED",
  /** Payment in flight: user has been shown checkout but no terminal event yet. */
  PENDING:  "PENDING",
  /** Provider has confirmed funds captured. Source of truth for ledger CREDIT. */
  SUCCESS:  "SUCCESS",
  /** Provider returned a terminal failure (declined, insufficient funds, etc). */
  FAILED:   "FAILED",
  /** The intent's expire_after / expire_by elapsed with no terminal event. */
  EXPIRED:  "EXPIRED",
  /** A previously SUCCESSful payment was refunded (full or partial). */
  REFUNDED: "REFUNDED",
} as const;

export type PaymentState = typeof PAYMENT_STATE[keyof typeof PAYMENT_STATE];

/**
 * Provider state strings we already see in PhonePe v2 and Razorpay v1.
 * Adapters can extend by importing PAYMENT_STATE and writing their own
 * switch, but this helper covers the most common cases.
 */
export function mapProviderState(raw: string | null | undefined): PaymentState {
  switch ((raw || "").toUpperCase()) {
    case "COMPLETED":
    case "CAPTURED":
    case "PAID":
    case "SUCCESS":
      return PAYMENT_STATE.SUCCESS;
    case "PENDING":
    case "PROCESSING":
    case "INITIATED":
      return PAYMENT_STATE.PENDING;
    case "CREATED":
      return PAYMENT_STATE.CREATED;
    case "FAILED":
    case "DECLINED":
    case "ERROR":
    case "CANCELLED":   // we treat user-cancellation as terminal failure for ledger purposes
      return PAYMENT_STATE.FAILED;
    case "EXPIRED":
    case "TIMEOUT":
      return PAYMENT_STATE.EXPIRED;
    case "REFUNDED":
    case "REVERSED":
      return PAYMENT_STATE.REFUNDED;
    default:
      return PAYMENT_STATE.PENDING;
  }
}

/**
 * Verification state for webhook events and status responses.
 *
 *   SIGNED              — signature/auth header was present and validated
 *   UNVERIFIED          — verification was skipped (e.g. status fetch over OAuth — trust the transport, not a signature)
 *   SIGNATURE_FAILED    — signature header was present but failed validation
 *
 * `SIGNATURE_FAILED` should never reach business logic; the webhook
 * route is expected to reject before calling the adapter. It is defined
 * so adapter tests can pin the exact failure shape.
 */
export type VerificationState = "SIGNED" | "UNVERIFIED" | "SIGNATURE_FAILED";

// ────────────────────────────────────────────────────────────────────────────
//  Result shapes (A-3)
// ────────────────────────────────────────────────────────────────────────────

export interface CreateIntentResult {
  provider: string;
  merchant_txn_id: string;
  checkout_url?: string | null;
  upi_intent_url?: string | null;
  qr_payload?: string | null;
  expires_at?: Date | null;
  gateway_txn_id?: string | null;
  provider_transaction_id?: string | null;
  provider_order_id?: string | null;
  provider_reference_id?: string | null;
  raw_response: any;
}

export interface WebhookVerificationResult {
  merchant_txn_id: string;
  gateway_txn_id?: string | null;
  provider_transaction_id?: string | null;
  provider_order_id?: string | null;
  provider_reference_id?: string | null;
  /** Canonical state. Kept as a string literal union for back-compat with existing call sites. */
  status: "SUCCESS" | "FAILED" | "PENDING" | "CANCELLED" | "EXPIRED";
  amount?: number | null;
  /** Provider's raw state string, preserved verbatim for forensics. */
  provider_state?: string | null;
  /** A-3 verification state of the webhook (SIGNED / UNVERIFIED / SIGNATURE_FAILED). */
  verification_state?: VerificationState;
  /** Provider-reported event timestamp, if available. */
  event_at?: Date | null;
  raw_event: any;
  tenant_id?: string | null;
}

export interface FetchStatusResult {
  status: "SUCCESS" | "FAILED" | "PENDING" | "CANCELLED" | "EXPIRED";
  gateway_txn_id?: string | null;
  provider_transaction_id?: string | null;
  provider_order_id?: string | null;
  provider_reference_id?: string | null;
  /** Provider's raw state string, preserved verbatim for forensics. */
  provider_state?: string | null;
  /** Verification state for the status fetch — usually UNVERIFIED (OAuth transport). */
  verification_state?: VerificationState;
  /** Provider-reported completion/settlement timestamp, if available. */
  completed_at?: Date | null;
  raw_status: any;
  tenant_id?: string | null;
}

/**
 * Refund result. Refunds are an OPTIONAL capability (see
 * `PaymentProvider.supportsRefunds`). Partial refunds are supported via
 * the `amount` parameter being less than the original transaction
 * amount. The adapter must round-trip the canonical refund state.
 */
export interface RefundResult {
  provider: string;
  /** Our identifier for this refund attempt (passed in, echoed back). */
  refund_idempotency_key: string;
  /** Provider's refund id. */
  provider_refund_id: string | null;
  /** Canonical state of this refund. */
  status: PaymentState;            // SUCCESS, PENDING, FAILED, or REFUNDED
  /** Rupees, positive. */
  amount: number;
  /** Whether this refunded the full original transaction. */
  is_full_refund: boolean;
  provider_state?: string | null;
  raw_response: any;
}

/**
 * Settlement metadata as reported by the provider. NOT the source of
 * truth for HMS owner liability — that lives in `owner_settlement_ledger`
 * and is provider-agnostic. This is purely a forensic / reconciliation
 * input so admins can cross-check provider-reported settlement against
 * what HMS independently computed.
 */
export interface SettlementMetadataResult {
  provider: string;
  merchant_txn_id: string;
  /** Provider's settlement id (UTR / settlement_id). */
  provider_settlement_id: string | null;
  /** When the provider claims funds were transferred. */
  settled_at: Date | null;
  /** Rupees actually credited to the merchant bank account (after fees). */
  net_amount: number | null;
  /** Provider's fee component. */
  fee_amount: number | null;
  /** GST on the fee. */
  tax_amount: number | null;
  /** Currency, default INR. */
  currency: string;
  raw_response: any;
}

// ────────────────────────────────────────────────────────────────────────────
//  Abstract adapter (A-1)
// ────────────────────────────────────────────────────────────────────────────

export abstract class PaymentProvider {
  constructor(protected config: any) {}

  // ── Required operations ────────────────────────────────────────────────

  abstract createIntent(data: {
    amount: number;
    merchant_txn_id: string;
    tenant_name: string;
    tenant_email?: string;
    tenant_phone?: string;
    metadata: any;
  }): Promise<CreateIntentResult>;

  abstract verifyWebhook(
    headers: Record<string, string>,
    body: string | Buffer,
  ): Promise<WebhookVerificationResult>;

  abstract fetchStatus(
    merchant_txn_id: string,
    gateway_txn_id?: string,
  ): Promise<FetchStatusResult>;

  // ── Optional capabilities (A-2) ─────────────────────────────────────────
  //
  // Adapters opt in by flipping the capability flag AND overriding the
  // corresponding method. The default implementations throw a typed
  // NOT_SUPPORTED error so callers can branch deterministically.

  /** Whether this adapter supports the refund() method. */
  readonly supportsRefunds: boolean = false;
  /** Whether this adapter supports the getSettlementMetadata() method. */
  readonly supportsSettlementMetadata: boolean = false;

  async refund(_params: {
    merchant_txn_id: string;
    provider_transaction_id?: string | null;
    amount: number;
    refund_idempotency_key: string;
    reason?: string;
    metadata?: any;
  }): Promise<RefundResult> {
    throw new Error(
      "NOT_SUPPORTED: refund() is not implemented for this provider. " +
      "Check provider.supportsRefunds before calling.",
    );
  }

  async getSettlementMetadata(_params: {
    merchant_txn_id: string;
    provider_transaction_id?: string | null;
  }): Promise<SettlementMetadataResult> {
    throw new Error(
      "NOT_SUPPORTED: getSettlementMetadata() is not implemented for this provider. " +
      "Check provider.supportsSettlementMetadata before calling.",
    );
  }
}
