import { NextRequest } from "next/server";
import { getSession, apiError } from "@/lib/auth";
import { resolveOwnerScope } from "@/lib/auth/resolve-operational-scope";
import { requireHostelBelongsToOwner } from "@/lib/security/scoped-query";
import { checkFixedWindowLimit } from "@/lib/redis/rate-limit";
import { prisma } from "@/lib/db";
import {
  streamExpensesCsv,
  streamExpensesXlsx,
  generateExpensesPdf,
  exportFilename,
  exportContentType,
  type ExpenseExportFormat,
  type ExpenseExportScope,
} from "@/lib/services/expense-export-service";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

const VALID_FORMATS: ExpenseExportFormat[] = ["csv", "xlsx", "pdf"];
const VALID_SCOPES: ExpenseExportScope[] = ["current_view", "all_matching", "selected"];

/**
 * Streams a CSV/XLSX file or generates a PDF report of expenses matching the exact same
 * filters as GET /api/expenses — built on the shared `buildExpenseLedgerWhere` query
 * builder in lib/services/expense-service.ts so exported data can never drift from what
 * the UI shows for the same filter state.
 */
export async function GET(req: NextRequest) {
  const session = await getSession(req);
  if (!session || !["OWNER", "ADMIN"].includes(session.role)) {
    return apiError("Forbidden", "FORBIDDEN", 403);
  }

  try {
    const scope = resolveOwnerScope(session);

    const rateLimit = await checkFixedWindowLimit({
      scope: "expenses:export",
      identifier: scope.owner_id,
      maxAttempts: 10,
      windowSeconds: 60,
    });
    if (!rateLimit.allowed) {
      return apiError("Rate limit exceeded: max 10 exports per minute", "TOO_MANY_REQUESTS", 429);
    }

    const params = req.nextUrl.searchParams;
    const format = params.get("format") as ExpenseExportFormat;
    if (!format || !VALID_FORMATS.includes(format)) {
      return apiError(`format must be one of: ${VALID_FORMATS.join(", ")}`, "VALIDATION_ERROR", 400);
    }

    const exportScope = (params.get("scope") || "all_matching") as ExpenseExportScope;
    if (!VALID_SCOPES.includes(exportScope)) {
      return apiError(`scope must be one of: ${VALID_SCOPES.join(", ")}`, "VALIDATION_ERROR", 400);
    }

    const hostelId = params.get("hostelId") || undefined;
    if (hostelId) await requireHostelBelongsToOwner(scope.owner_id, hostelId);

    const categories = params.get("categories");
    const recurringParam = params.get("recurring");
    const recurring = recurringParam === null || recurringParam === "" ? undefined : recurringParam === "true";
    const amountMinParam = params.get("amountMin");
    const amountMaxParam = params.get("amountMax");
    const amountMin = amountMinParam !== null && amountMinParam !== "" ? Number(amountMinParam) : undefined;
    const amountMax = amountMaxParam !== null && amountMaxParam !== "" ? Number(amountMaxParam) : undefined;
    if (amountMin !== undefined && !Number.isFinite(amountMin)) {
      return apiError("amountMin must be a valid number", "VALIDATION_ERROR", 400);
    }
    if (amountMax !== undefined && !Number.isFinite(amountMax)) {
      return apiError("amountMax must be a valid number", "VALIDATION_ERROR", 400);
    }

    const ids = params.get("ids")?.split(",").map((s) => s.trim()).filter(Boolean) || [];
    if (exportScope === "selected" && ids.length === 0) {
      return apiError("scope=selected requires at least one id", "VALIDATION_ERROR", 400);
    }

    // Owner's display name for the report's "Generated by" line — resolved here (the route
    // has the session) so expense-export-service.ts stays auth-agnostic. Falls back to the
    // session email if the profile lookup comes back empty for any reason.
    const generatedByProfile = await prisma.profile.findUnique({ where: { id: session.sub }, select: { name: true } });
    const generatedByName = generatedByProfile?.name || session.email || "Owner";

    const exportRequest = {
      ownerId: scope.owner_id,
      filters: {
        range: params.get("range") || undefined,
        startDate: params.get("startDate") || undefined,
        endDate: params.get("endDate") || undefined,
        hostelId,
        categories: categories ? categories.split(",").filter(Boolean) : undefined,
        status: params.get("status") || undefined,
        sort: params.get("sort") || undefined,
        search: params.get("search") || undefined,
        recurring,
        amountMin,
        amountMax,
      },
      scope: exportScope,
      ids: exportScope === "selected" ? ids : undefined,
      limit: params.get("limit") ? Number(params.get("limit")) : undefined,
      offset: params.get("offset") ? Number(params.get("offset")) : undefined,
      filterSnapshot: {
        vendor: params.get("vendor") || undefined,
        paymentMethod: params.get("paymentMethod") || undefined,
      },
      generatedByName,
    };

    const filename = exportFilename(format);
    const headers = {
      "Content-Type": exportContentType(format),
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "private, no-store",
    };

    if (format === "csv") {
      return new Response(streamExpensesCsv(exportRequest), { status: 200, headers });
    }
    if (format === "xlsx") {
      return new Response(await streamExpensesXlsx(exportRequest), { status: 200, headers });
    }
    const pdfBytes = await generateExpensesPdf(exportRequest);
    return new Response(pdfBytes as any, { status: 200, headers });
  } catch (error: any) {
    const msg = String(error?.message || "");
    if (msg.startsWith("VALIDATION")) return apiError(msg.split(": ")[1] ?? msg, "VALIDATION_ERROR", 400);
    return apiError(msg || "Failed to export expenses");
  }
}
